#!/usr/bin/env node

const cli = require("./cli");

cli.cli(process.argv[2], {
    validate: process.argv.includes('--validate'),
    stats: process.argv.includes('--stats'),
    validateAndStats: process.argv.includes('--validate') && process.argv.includes('--stats'),
});